// Package jobs has seed jobs
package jobs

import (
	"github.com/jinzhu/gorm"
	"github.com/mortenoj/go-graphql-template/internal/orm/models"
	"gopkg.in/gormigrate.v1"
)

// SeedUsers defines job for seeding users table
func SeedUsers() *gormigrate.Migration {
	var (
		uname       = "user_seeded"
		fname       = "Seeded"
		lname       = "User"
		nname       = "SeededUser"
		description = "This user was generated by migrations"
		location    = "Seeded user location"

		firstUser *models.User = &models.User{
			Email:       "test@test.com",
			Name:        &uname,
			FirstName:   &fname,
			LastName:    &lname,
			NickName:    &nname,
			Description: &description,
			Location:    &location,
		}
	)

	return &gormigrate.Migration{
		ID: "SEED_USERS",
		Migrate: func(db *gorm.DB) error {
			return db.Create(&firstUser).Error
		},
		Rollback: func(db *gorm.DB) error {
			return db.Delete(&firstUser).Error
		},
	}
}
